import 'package:flutter/material.dart';
import 'workout_models.dart';

final List<Exercise> predefinedExercises = [
  Exercise(
    name: 'Push-ups',
    sets: 3,
    reps: '10-12',
    rest: '60s',
    icon: Icons.fitness_center,
    instructions: 'Keep your body in a straight line from head to heels',
    targetMuscles: 'Chest, Triceps, Shoulders',
  ),
  Exercise(
    name: 'Squats',
    sets: 3,
    reps: '12-15',
    rest: '60s',
    icon: Icons.fitness_center,
    instructions: 'Keep your chest up and knees behind your toes',
    targetMuscles: 'Quadriceps, Glutes',
  ),
  Exercise(
    name: 'Plank',
    sets: 3,
    reps: '30s',
    rest: '45s',
    icon: Icons.accessibility_new,
    instructions: 'Hold your body in a straight line from head to heels',
    targetMuscles: 'Core, Shoulders',
  ),
  Exercise(
    name: 'Lunges',
    sets: 3,
    reps: '10-12 each leg',
    rest: '60s',
    icon: Icons.fitness_center,
    instructions: 'Step forward and lower your back knee toward the ground',
    targetMuscles: 'Quadriceps, Glutes, Hamstrings',
  ),
  Exercise(
    name: 'Burpees',
    sets: 3,
    reps: '10',
    rest: '60s',
    icon: Icons.flash_on,
    instructions: 'Squat, jump back to plank, jump forward, jump up',
    targetMuscles: 'Full Body',
  ),
  Exercise(
    name: 'Mountain Climbers',
    sets: 3,
    reps: '30s',
    rest: '30s',
    icon: Icons.directions_run,
    instructions: 'Alternate bringing your knees to your chest',
    targetMuscles: 'Core, Shoulders',
  ),
  Exercise(
    name: 'Jumping Jacks',
    sets: 3,
    reps: '30s',
    rest: '30s',
    icon: Icons.fitness_center,
    instructions: 'Jump while raising your arms overhead',
    targetMuscles: 'Full Body',
  ),
  Exercise(
    name: 'Bicep Curls',
    sets: 3,
    reps: '12-15',
    rest: '45s',
    icon: Icons.fitness_center,
    instructions: 'Keep your elbows close to your body throughout the movement',
    targetMuscles: 'Biceps',
  ),
  Exercise(
    name: 'Tricep Dips',
    sets: 3,
    reps: '10-12',
    rest: '60s',
    icon: Icons.fitness_center,
    instructions:
        'Lower your body until your upper arms are parallel to the ground',
    targetMuscles: 'Triceps, Chest',
  ),
  Exercise(
    name: 'Shoulder Press',
    sets: 3,
    reps: '10-12',
    rest: '75s',
    icon: Icons.fitness_center,
    instructions: 'Press the weights overhead while keeping your core tight',
    targetMuscles: 'Shoulders, Triceps',
  ),
];
